[package]
name = "jlrunner"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
thiserror.workspace = true
jl-sg = { path = "../../crates/jl-sg" }
jl-uboot = { path = "../../crates/jl-uboot" }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
